# Generated by Django 5.0.2 on 2024-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(upload_to='images/category')),
                ('text', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=20)),
            ],
        ),
    ]
