# Generated by Django 5.0.2 on 2024-02-19 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageUrl',
            field=models.FileField(upload_to='images/category', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
