# Generated by Django 5.0.2 on 2024-02-19 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.FileField(upload_to='images/product', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
